import { Platform, StyleSheet } from 'react-native';
import type { PrinterConnection, PrinterSettings } from '../../printerService';
export type AppScreen = 'home' | 'order' | 'menu' | 'history' | 'printer';
export const ROUTES = { home: '/', order: '/order', menu: '/menu', history: '/history', printer: '/printer' } as const;
export const PLATES = Array.from({ length: 10 }, (_, index) => String(index + 1));
export const CONNECTIONS: { value: PrinterConnection; label: string }[] = [
  { value: 'system', label: Platform.OS === 'ios' ? 'Sistema iOS (AirPrint)' : 'Sistema Android' },
  { value: 'bluetooth', label: 'Bluetooth' },
  { value: 'wifi', label: 'Wi-Fi / rede' },
  { value: 'usb', label: 'USB / OTG' },
];
export const DEFAULT_PRINTER_SETTINGS: PrinterSettings = { connection: 'system', name: '', address: '', port: '9100', paperWidth: '80' };
export const QUICK_NOTES = ['Sem cebola', 'Pouco sal', 'Bem passado'];

export const TABS: { screen: AppScreen; label: string; title: string; icon: string; hint: string }[] = [
  { screen: 'home', label: 'Início', title: 'Início', icon: '⌂', hint: 'Visão geral' },
  { screen: 'order', label: 'Pedido', title: 'Novo pedido', icon: '+', hint: 'Montar uma comanda' },
  { screen: 'menu', label: 'Cardápio', title: 'Cardápio', icon: '≡', hint: 'Produtos e categorias' },
  { screen: 'history', label: 'Histórico', title: 'Histórico', icon: '◷', hint: 'Consultar e reimprimir' },
  { screen: 'printer', label: 'Ajustes', title: 'Configurações', icon: '⚙', hint: 'Impressora e atualização' },
];

export const COLORS = {
  background: '#F5F3EF', surface: '#FFFFFF', ink: '#223B35', muted: '#62716B',
  border: '#DBE2DC', green: '#214B40', greenSoft: '#E8F1EC',
  primary: '#AE4328', primarySoft: '#FCEBE3', placeholder: '#6C7771',
};

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: { flex: 1, backgroundColor: COLORS.background },
  pressed: { opacity: 0.7 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 20, paddingVertical: 16, width: '100%', maxWidth: 1160, alignSelf: 'center' },
  logoButton: { borderRadius: 16, overflow: 'hidden', width: 56, height: 56 },
  logoImage: { width: '100%', height: '100%' },
  headerWide: { paddingVertical: 10 },
  logoButtonWide: { width: 44, height: 44, borderRadius: 12 },
  headerTitle: { flex: 1, minWidth: 0 },
  eyebrow: { color: COLORS.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.8, marginBottom: 4 },
  title: { color: COLORS.ink, fontSize: 25, fontWeight: '800', letterSpacing: -0.6 },
  headerBadge: { backgroundColor: COLORS.greenSoft, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20 },
  headerBadgeText: { color: COLORS.green, fontSize: 12, fontWeight: '600' },
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 28, alignItems: 'center' },
  contentFrame: { width: '100%', maxWidth: 1120 },
  hero: { backgroundColor: COLORS.green, borderRadius: 24, padding: 24 },
  heroEyebrow: { color: '#BDD5CA', fontSize: 10, fontWeight: '800', letterSpacing: 1.3, marginBottom: 14 },
  heroTitle: { color: '#FFFFFF', fontSize: 29, lineHeight: 36, fontWeight: '800', maxWidth: 460, letterSpacing: -0.8 },
  heroTitleWide: { fontSize: 28, lineHeight: 34, maxWidth: 620 },
  heroWide: { padding: 18, borderRadius: 18 },
  heroButtonWide: { marginTop: 14, paddingVertical: 10, minHeight: 44, maxWidth: 300 },
  sectionTitleWide: { marginTop: 18, marginBottom: 10 },
  heroDescription: { color: '#DFEBE4', fontSize: 14, lineHeight: 22, marginTop: 12, maxWidth: 440 },
  heroButton: { backgroundColor: COLORS.primary, borderRadius: 14, paddingHorizontal: 20, paddingVertical: 15, marginTop: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', maxWidth: 400 },
  heroButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  heroArrow: { color: '#FFFFFF', fontSize: 24 },
  sectionTitle: { color: COLORS.ink, fontSize: 20, fontWeight: '800', marginTop: 26, marginBottom: 14 },
  mainMenu: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  mainMenuButton: { flexBasis: '45%', flexGrow: 1, backgroundColor: COLORS.surface, borderColor: COLORS.border, borderWidth: 1, borderRadius: 18, padding: 16 },
  mainMenuButtonWide: { flexBasis: '22%', padding: 12, borderRadius: 14 },
  menuIconBadgeWide: { width: 32, height: 32, borderRadius: 10, marginBottom: 8 },
  mainMenuIconWide: { fontSize: 20 },
  menuIconBadge: { width: 40, height: 40, borderRadius: 12, backgroundColor: COLORS.primarySoft, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  mainMenuIcon: { color: COLORS.primary, fontSize: 25, fontWeight: '600' },
  mainMenuTitle: { color: COLORS.ink, fontSize: 15, fontWeight: '800' },
  mainMenuHint: { color: COLORS.muted, fontSize: 12, lineHeight: 18, marginTop: 5 },
  homeFooter: { paddingVertical: 22, paddingHorizontal: 12 },
  homeFooterText: { color: COLORS.muted, fontSize: 12, lineHeight: 19, textAlign: 'center' },
  columns: { gap: 20 },
  columnsWide: { flexDirection: 'row', alignItems: 'flex-start' },
  column: { minWidth: 0 },
  columnWide: { flex: 1 },
  panel: { backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 20, padding: 18 },
  panelTitle: { color: COLORS.ink, fontSize: 20, fontWeight: '800' },
  settingsIntro: { color: COLORS.muted, fontSize: 14, lineHeight: 22, marginTop: 8, marginBottom: 20 },
  label: { color: COLORS.ink, fontSize: 13, fontWeight: '700', marginBottom: 10 },
  fieldLabel: { color: COLORS.ink, fontSize: 13, fontWeight: '600', marginTop: 16, marginBottom: 8 },
  input: { backgroundColor: '#F8FAF8', borderColor: COLORS.border, borderWidth: 1, borderRadius: 12, color: COLORS.ink, fontSize: 15, minHeight: 48, paddingHorizontal: 12, paddingVertical: 12 },
  inputError: { borderColor: '#A33024' },
  errorText: { color: '#A33024', fontSize: 13, marginTop: 8 },
  spacedInput: { marginTop: 12 },
  helperText: { color: COLORS.muted, fontSize: 12, lineHeight: 19, marginTop: 10 },
  connectionList: { gap: 8 },
  connectionOption: { minHeight: 48, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: COLORS.border, borderRadius: 12, padding: 14 },
  selectedConnection: { backgroundColor: COLORS.green, borderColor: COLORS.green },
  connectionText: { color: COLORS.ink, fontSize: 14, fontWeight: '700' },
  selectedConnectionText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  paperOptions: { flexDirection: 'row', gap: 10 },
  paperOption: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderColor: COLORS.border, borderWidth: 1, borderRadius: 12, padding: 14 },
  menuGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  menuEditCard: { width: '100%', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 18, padding: 16 },
  menuEditCardWide: { width: '48%', flexGrow: 1, flexBasis: '46%' },
  menuEditRow: { flexDirection: 'row', gap: 12 },
  menuEditField: { flex: 1, minWidth: 0 },
  priceField: { flex: 0.65, minWidth: 82 },
  menuEditActions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 8, marginTop: 16 },
  removeButton: { backgroundColor: '#FCECE8', borderRadius: 10, minHeight: 44, justifyContent: 'center', paddingHorizontal: 14 },
  removeButtonText: { color: '#A33024', fontSize: 13, fontWeight: '700' },
  sendButton: { alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary, borderRadius: 14, minHeight: 52, marginTop: 18, padding: 16 },
  sendButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', textAlign: 'center' },
  sendButtonHint: { color: '#FFE8DE', fontSize: 12, marginTop: 5, textAlign: 'center' },
  secondaryWideButton: { alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.greenSoft, borderColor: '#D2E3D8', borderWidth: 1, borderRadius: 14, minHeight: 50, marginTop: 12, padding: 14 },
  secondaryButtonText: { color: COLORS.green, fontSize: 14, fontWeight: '700', textAlign: 'center' },
  plateList: { gap: 8, paddingBottom: 4 },
  plate: { alignItems: 'center', justifyContent: 'center', borderColor: COLORS.border, borderWidth: 1, borderRadius: 12, minHeight: 46, minWidth: 46, padding: 10 },
  selectedPlate: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  plateText: { color: COLORS.ink, fontSize: 16, fontWeight: '700' },
  selectedPlateText: { color: '#FFFFFF' },
  categoryList: { gap: 8, paddingBottom: 14 },
  category: { borderColor: COLORS.border, borderWidth: 1, borderRadius: 22, minHeight: 44, justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 10, backgroundColor: COLORS.surface },
  selectedCategory: { backgroundColor: COLORS.green, borderColor: COLORS.green },
  categoryText: { color: COLORS.muted, fontSize: 13, fontWeight: '700' },
  selectedCategoryText: { color: '#FFFFFF' },
  productCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: COLORS.surface, borderColor: COLORS.border, borderWidth: 1, borderRadius: 16, marginBottom: 10, padding: 16 },
  productInfo: { flex: 1, minWidth: 0 },
  cardTitle: { color: COLORS.ink, fontSize: 16, fontWeight: '700', lineHeight: 23 },
  mutedText: { color: COLORS.muted, fontSize: 13, lineHeight: 19, marginTop: 4 },
  priceText: { color: COLORS.green, fontSize: 15, fontWeight: '800', marginTop: 8 },
  productArrow: { width: 44, height: 44, borderRadius: 14, backgroundColor: COLORS.primarySoft, alignItems: 'center', justifyContent: 'center' },
  productArrowText: { color: COLORS.primary, fontSize: 25, fontWeight: '700' },
  orderHeader: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 16 },
  itemCount: { backgroundColor: COLORS.greenSoft, color: COLORS.green, borderRadius: 12, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6, fontSize: 12, fontWeight: '700' },
  emptyCard: { backgroundColor: '#F5F8F5', borderRadius: 14, padding: 22 },
  emptyTitle: { color: COLORS.ink, fontSize: 16, fontWeight: '700', marginBottom: 8 },
  emptyText: { color: COLORS.muted, fontSize: 14, lineHeight: 22 },
  orderCard: { borderBottomColor: COLORS.border, borderBottomWidth: 1, paddingBottom: 20, marginBottom: 18 },
  orderLine: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 8, marginTop: 8 },
  quantityControl: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  quantityButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: COLORS.greenSoft },
  quantityText: { color: COLORS.green, fontSize: 22, fontWeight: '700' },
  quantity: { color: COLORS.ink, fontSize: 16, fontWeight: '800', minWidth: 22, textAlign: 'center' },
  quickNotes: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  noteChip: { backgroundColor: COLORS.greenSoft, borderRadius: 12, minHeight: 44, justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 10 },
  noteChipText: { color: COLORS.green, fontSize: 12, fontWeight: '600' },
  totalRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 8, marginTop: 4 },
  totalLabel: { color: COLORS.muted, fontSize: 14 },
  totalText: { color: COLORS.ink, fontSize: 22, fontWeight: '800' },
  historyCard: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 16, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 18, marginBottom: 12, padding: 18 },
  addButton: { backgroundColor: COLORS.greenSoft, borderRadius: 12, minHeight: 44, justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 12 },
  addButtonText: { color: COLORS.green, fontSize: 13, fontWeight: '700' },
  navBackground: { backgroundColor: COLORS.surface, borderTopColor: COLORS.border, borderTopWidth: 1 },
  bottomNav: { flexDirection: 'row', gap: 4, paddingHorizontal: 8, paddingVertical: 8, width: '100%', maxWidth: 760, alignSelf: 'center' },
  bottomNavButton: { alignItems: 'center', justifyContent: 'center', flex: 1, minHeight: 58, borderRadius: 14, paddingVertical: 7, paddingHorizontal: 2 },
  activeBottomNavButton: { backgroundColor: COLORS.primarySoft },
  bottomNavIcon: { color: COLORS.muted, fontSize: 23, fontWeight: '600', marginBottom: 3 },
  bottomNavWide: { maxWidth: 640, paddingVertical: 4 },
  bottomNavButtonWide: { minHeight: 48, paddingVertical: 4 },
  bottomNavIconWide: { fontSize: 19 },
  bottomNavText: { color: COLORS.muted, fontSize: 10, fontWeight: '700', textAlign: 'center' },
  activeBottomNavText: { color: COLORS.primary },
  feedbackToast: { marginHorizontal: 20, marginBottom: 8, padding: 14, borderRadius: 14, borderWidth: 1 },
  feedbackSuccess: { backgroundColor: '#E6F2E9', borderColor: '#9CBDA8' },
  feedbackError: { backgroundColor: '#FCECE8', borderColor: '#DFA699' },
  feedbackTitle: { color: COLORS.ink, fontSize: 14, fontWeight: '800' },
  feedbackMessage: { color: COLORS.ink, fontSize: 13, lineHeight: 19, marginTop: 4 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(18,35,29,0.55)', justifyContent: 'flex-end' },
  modalBackdropWide: { justifyContent: 'center', alignItems: 'center', padding: 24 },
  productModal: { backgroundColor: COLORS.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '90%', width: '100%' },
  productModalWide: { maxWidth: 560, borderRadius: 24, overflow: 'hidden' },
  modalContent: { padding: 24 },
  modalEyebrow: { color: COLORS.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1.2, marginBottom: 10 },
  modalTitle: { color: COLORS.ink, fontSize: 24, fontWeight: '800', lineHeight: 31 },
  modalInput: { minHeight: 100, textAlignVertical: 'top' },
  cancelButton: { alignItems: 'center', justifyContent: 'center', minHeight: 48, marginTop: 8 },
  cancelButtonText: { color: COLORS.muted, fontSize: 14, fontWeight: '700' },
});
