const logo = `<svg viewBox="0 0 512 512" role="img" aria-label="Logo do app" xmlns="http://www.w3.org/2000/svg"><rect width="512" height="512" rx="112" fill="#202322"/><path d="M112 292c-16-13-23-34-17-54 6-21 25-35 47-36-2-7-3-14-3-21 0-40 32-72 72-72 18 0 35 7 48 18 14-18 36-29 60-29 41 0 74 33 74 74 0 9-2 17-5 25 4-1 8-1 12-1 25 0 45 20 45 45 0 19-12 36-29 42v30H112z" fill="#fffaf0" stroke="#d35d32" stroke-width="18" stroke-linejoin="round"/><path d="M112 283h304v91c0 24-19 43-43 43H155c-24 0-43-19-43-43z" fill="#fffaf0" stroke="#d35d32" stroke-width="18"/></svg>`;

const css = `:root{font-family:system-ui,-apple-system,sans-serif;color:#223b35;background:#f5f3ef}*{box-sizing:border-box}body{margin:0;min-height:100vh}.shell{max-width:960px;margin:0 auto;padding:28px 20px 48px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:32px}.brand{display:flex;align-items:center;gap:14px}.brand svg{width:56px;height:56px;flex:none}.brand-name{font-size:20px;font-weight:800;letter-spacing:-.03em}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#687c72}.card{background:#fff;border:1px solid #dbe2dc;border-radius:22px;box-shadow:0 12px 30px #1b3a2b0d;padding:28px}.hero{background:#214b40;color:#fff;border-radius:22px;padding:30px;margin-bottom:18px}.hero .eyebrow{color:#c0d9cf}h1{font-size:clamp(28px,4vw,42px);line-height:1.15;margin:12px 0}h2{font-size:21px;margin:0 0 10px}p{line-height:1.5;margin:0}.hero p{color:#e0ebe5;max-width:680px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.actions{display:grid;gap:12px;margin-top:20px}button,.action{font:inherit;min-height:48px;border-radius:12px;border:0;padding:12px 16px;cursor:pointer;text-align:center;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;font-weight:700}.primary{background:#ae4328;color:#fff}.secondary{background:#e8f1ec;color:#214b40}.quiet{background:transparent;color:#214b40;border:1px solid #b9c9bf}.danger{color:#963821}.topbar button{min-height:44px}button:hover,.action:hover{filter:brightness(.94)}button:disabled{opacity:.55;cursor:wait}button:focus-visible,input:focus-visible,.action:focus-visible{outline:3px solid #ae4328;outline-offset:2px}.result{margin-top:18px;padding:16px;border-radius:14px;background:#f5f8f5;white-space:pre-wrap;overflow-wrap:anywhere;min-height:52px}.result:empty{display:none}.muted{color:#62716b;font-size:14px}.note{margin-top:18px}.login{max-width:440px;margin:5vh auto 0}.login .brand{margin-bottom:22px}.field{display:block;font-weight:700;margin:18px 0 8px}input{width:100%;min-height:50px;border:1px solid #cbd8cf;border-radius:12px;padding:12px 14px;font:inherit;background:#f8faf8;color:#223b35}.login button{width:100%;margin-top:22px}.error{color:#963821;margin-top:12px}.logs{display:grid;gap:8px;max-height:340px;overflow:auto}.log{padding:10px;border-bottom:1px solid #dbe2dc;font-size:13px}footer{margin-top:20px;color:#62716b;font-size:13px}@media(max-width:640px){.shell{padding:16px 12px 28px}.topbar{margin-bottom:20px}.brand svg{width:46px;height:46px}.brand-name{font-size:17px}.card,.hero{padding:20px;border-radius:17px}.grid{grid-template-columns:1fr}.login{margin:4vh auto 0}}`;

function page(content, nonce) {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BistroHub · Painel</title><style nonce="${nonce}">${css}</style></head><body>${content}</body></html>`;
}

function brand() {
  return `<div class="brand">${logo}<div><div class="eyebrow">Painel administrativo</div><div class="brand-name">BistroHub</div></div></div>`;
}

export function loginPage(nonce, message = '') {
  return page(`<main class="shell"><section class="card login">${brand()}<h1>Entrar no painel</h1><p class="muted">Entre para consultar a senha semanal e os registros do sistema.</p><form action="/admin/login" method="post"><label class="field" for="username">Usuário ou e-mail</label><input id="username" name="username" autocomplete="username" required maxlength="120"><label class="field" for="password">Senha do painel</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="256"><button class="primary" type="submit">Entrar</button></form>${message ? `<p class="error" role="alert">${message}</p>` : ''}</section></main>`, nonce);
}

export function panelPage(nonce) {
  return page(`<main class="shell"><header class="topbar">${brand()}<button class="quiet" id="logout" type="button">Sair</button></header><section class="hero"><div class="eyebrow">Acesso do administrador</div><h1>Senha semanal do admin</h1><p>Consulte ou atualize a senha usada nos tablets. Sua sessão expira após uma hora sem atividade.</p></section><div class="grid"><section class="card"><h2>Senha de acesso</h2><p class="muted">A troca manual vale até a próxima segunda-feira. Aparelhos offline mantêm a última senha recebida.</p><div class="actions"><button class="primary" id="view" type="button">Consultar senha</button><button class="secondary" id="rotate" type="button">Gerar nova senha agora</button></div><div id="password-result" class="result" role="status" aria-live="polite"></div></section><section class="card"><h2>Registros do sistema</h2><p class="muted">Consulte os eventos recentes de erro e impressão para acompanhar os tablets.</p><div class="actions"><button class="secondary" id="logs-button" type="button">Consultar logs</button></div><div id="logs-result" class="result logs" role="status" aria-live="polite"></div></section></div><footer>Por segurança, a senha mostrada nesta página desaparece após um minuto.</footer></main><script nonce="${nonce}">
const idleMs=3600000;let lastActivity=Date.now(),lastRenew=Date.now();const passwordResult=document.querySelector('#password-result'),logsResult=document.querySelector('#logs-result');let clearPassword;
async function leave(reason){passwordResult.textContent='';try{await fetch('/admin/logout',{method:'POST',credentials:'same-origin',cache:'no-store'})}finally{location.replace('/admin?'+reason+'=1')}}
function expired(){return Date.now()-lastActivity>=idleMs}
function activity(){if(expired()){void leave('expired');return}lastActivity=Date.now();if(Date.now()-lastRenew>300000){lastRenew=Date.now();void fetch('/admin/session',{credentials:'same-origin',cache:'no-store'}).then(response=>{if(response.status===401)location.replace('/admin?expired=1')}).catch(()=>{})}}
for(const event of ['pointerdown','keydown','touchstart','scroll'])document.addEventListener(event,activity,{passive:true});setInterval(()=>{if(expired())void leave('expired')},30000);document.addEventListener('visibilitychange',()=>{passwordResult.textContent='';if(!document.hidden&&expired())void leave('expired')});
async function request(url,options={}){if(expired()){await leave('expired');return null}const response=await fetch(url,{credentials:'same-origin',cache:'no-store',...options});if(response.status===401){location.replace('/admin?expired=1');return null}if(!response.ok)throw Error();return response.json()}
document.querySelector('#view').addEventListener('click',()=>void showPassword(false));document.querySelector('#rotate').addEventListener('click',()=>void showPassword(true));async function showPassword(rotate){if(rotate&&!confirm('Gerar outra senha agora? Os aparelhos conectados passarão a usar a nova senha.'))return;const buttons=[document.querySelector('#view'),document.querySelector('#rotate')];buttons.forEach(button=>button.disabled=true);passwordResult.textContent='Consultando…';try{const data=await request('/auth/admin/password',{method:rotate?'POST':'GET'});if(!data)return;passwordResult.textContent='Usuário: admin\\nSenha: '+data.password+'\\nPróxima troca: '+new Date(data.nextRotation).toLocaleString('pt-BR');clearTimeout(clearPassword);clearPassword=setTimeout(()=>{passwordResult.textContent=''},60000)}catch{passwordResult.textContent='Não foi possível consultar. Confira a conexão.'}finally{buttons.forEach(button=>button.disabled=false)}}
document.querySelector('#logs-button').addEventListener('click',async()=>{logsResult.textContent='Carregando…';try{const rows=await request('/admin/logs');if(!rows)return;logsResult.textContent='';if(!rows.length){logsResult.textContent='Nenhum registro recente.';return}for(const row of rows){const item=document.createElement('div');item.className='log';item.textContent=new Date(row.created_at).toLocaleString('pt-BR')+' · '+row.event+' · '+row.code+(row.order_id?' · Pedido '+row.order_id:'');logsResult.appendChild(item)}}catch{logsResult.textContent='Não foi possível consultar os registros.'}});
document.querySelector('#logout').addEventListener('click',()=>void leave('loggedout'));
</script>`, nonce);
}
