const logo = `<svg viewBox="0 0 512 512" role="img" aria-label="Logo do app" xmlns="http://www.w3.org/2000/svg"><rect width="512" height="512" rx="112" fill="#202322"/><path d="M112 292c-16-13-23-34-17-54 6-21 25-35 47-36-2-7-3-14-3-21 0-40 32-72 72-72 18 0 35 7 48 18 14-18 36-29 60-29 41 0 74 33 74 74 0 9-2 17-5 25 4-1 8-1 12-1 25 0 45 20 45 45 0 19-12 36-29 42v30H112z" fill="#fffaf0" stroke="#d35d32" stroke-width="18" stroke-linejoin="round"/><path d="M112 283h304v91c0 24-19 43-43 43H155c-24 0-43-19-43-43z" fill="#fffaf0" stroke="#d35d32" stroke-width="18"/></svg>`;
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);

const css = `
:root{font-family:system-ui,-apple-system,sans-serif;color:#223b35;background:#f5f3ef}*{box-sizing:border-box}body{margin:0;min-height:100vh}
.shell{max-width:960px;margin:0 auto;padding:20px 20px 48px}.topbar{position:sticky;top:0;z-index:2;display:flex;align-items:center;gap:18px;flex-wrap:wrap;margin:-20px -20px 26px;padding:16px 20px;background:#f5f3ef;border-bottom:1px solid #dbe2dc}
.brand{display:flex;align-items:center;gap:14px}.brand svg{width:52px;height:52px;flex:none}.brand-name{font-size:20px;font-weight:800;letter-spacing:-.03em}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#687c72}
.nav{display:flex;align-items:center;flex-wrap:wrap;gap:7px;margin-left:auto}.nav a{display:inline-flex;align-items:center;min-height:42px;padding:8px 13px;border-radius:11px;text-decoration:none;color:#214b40;font-weight:700;font-size:14px}.nav a[aria-current=page]{background:#214b40;color:#fff}
.card{background:#fff;border:1px solid #dbe2dc;border-radius:22px;box-shadow:0 12px 30px #1b3a2b0d;padding:28px}.hero{background:#214b40;color:#fff;border-radius:22px;padding:26px;margin-bottom:18px}.hero .eyebrow{color:#c0d9cf}h1{font-size:clamp(28px,4vw,40px);line-height:1.15;margin:10px 0}h2{font-size:22px;margin:0 0 10px}p{line-height:1.5;margin:0}.hero p{color:#e0ebe5;max-width:680px}
.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}button{font:inherit;min-height:46px;border-radius:12px;border:0;padding:11px 16px;cursor:pointer;text-align:center;font-weight:700}.primary{background:#ae4328;color:#fff}.secondary{background:#e8f1ec;color:#214b40}.quiet{background:transparent;color:#214b40;border:1px solid #b9c9bf}button:hover{filter:brightness(.94)}button:disabled{opacity:.55;cursor:wait}button:focus-visible,input:focus-visible,.nav a:focus-visible{outline:3px solid #ae4328;outline-offset:2px}
.result{margin-top:18px;padding:16px;border-radius:14px;background:#f5f8f5;white-space:pre-wrap;overflow-wrap:anywhere;min-height:52px}.result:empty{display:none}.muted{color:#62716b;font-size:14px}.login{max-width:440px;margin:5vh auto 0}.login .brand{margin-bottom:22px}.field{display:block;font-weight:700;margin:18px 0 8px}input{width:100%;min-height:50px;border:1px solid #cbd8cf;border-radius:12px;padding:12px 14px;font:inherit;background:#f8faf8;color:#223b35}.login button{width:100%;margin-top:22px}.error{color:#963821;margin-top:12px}.success{color:#214b40;margin-top:12px}.password-card{margin-top:18px;max-width:580px}.password-card button{margin-top:20px}.logs{display:grid;gap:8px;max-height:50vh;overflow:auto}.log{padding:10px;border-bottom:1px solid #dbe2dc;font-size:13px}footer{margin-top:20px;color:#62716b;font-size:13px}.view[hidden]{display:none}
@media(max-width:640px){.shell{padding:16px 12px 28px}.topbar{margin:-16px -12px 20px;padding:12px}.brand svg{width:42px;height:42px}.brand-name{font-size:17px}.nav{margin-left:0;width:100%}.nav a{font-size:12px;padding:7px 9px}.card,.hero{padding:20px;border-radius:17px}.login{margin:4vh auto 0}}
`;

function page(content, nonce) {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BistroHub · Painel</title><style nonce="${nonce}">${css}</style></head><body>${content}</body></html>`;
}

function brand() {
  return `<div class="brand">${logo}<div><div class="eyebrow">Painel administrativo</div><div class="brand-name">BistroHub</div></div></div>`;
}

export function loginPage(nonce, message = '', csrf = '') {
  return page(`<main class="shell"><section class="card login">${brand()}<h1>Entrar no painel</h1><p class="muted">Entre para consultar a senha semanal e os registros do sistema.</p><form action="/admin/login" method="post"><input type="hidden" name="csrf" value="${csrf}"><label class="field" for="storeId">Identificador da loja</label><input id="storeId" name="storeId" required maxlength="40" value="seabra-1" autocapitalize="none"><label class="field" for="username">Usuário ou e-mail</label><input id="username" name="username" autocomplete="username" required maxlength="120"><label class="field" for="password">Senha do painel</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="256"><button class="primary" type="submit">Entrar</button></form>${message ? `<p class="error" role="alert">${message}</p>` : ''}</section></main>`, nonce);
}

export function panelPage(nonce, store = { id: 'seabra-1', name: 'Seabra 1' }) {
  return page(`<main class="shell"><header class="topbar">${brand()}<span class="muted">Loja: ${escapeHtml(store.name)} (${escapeHtml(store.id)})</span><nav class="nav" aria-label="Menu do painel"><a href="#password" data-view="password">Gerenciar senha</a><a href="#errors" data-view="errors">Logs do sistema</a><a href="#printing" data-view="printing">Logs de impressão</a><button class="quiet" id="logout" type="button">Sair</button></nav></header>
<section class="view" id="password"><div class="hero"><div class="eyebrow">Acesso do administrador</div><h1>Gerenciar senhas</h1><p>Consulte separadamente a senha semanal, a senha de Ajustes e o acesso ao painel BistroHub.</p></div><div class="card"><h2>Senha semanal do aplicativo</h2><p class="muted">A troca manual vale até a próxima segunda-feira. Aparelhos offline mantêm a última senha recebida.</p><div class="actions"><button class="primary" id="view" type="button">Consultar senha</button><button class="secondary" id="rotate" type="button">Gerar nova senha agora</button></div><div id="password-result" class="result" role="status" aria-live="polite"></div></div><div class="card password-card"><h2>Senha de Ajustes</h2><p class="muted">Calculada com a data e a hora local deste dispositivo, no formato de 12 horas. Confira se o tablet está com a mesma data e hora.</p><div class="actions"><button class="secondary" id="view-settings-password" type="button">Consultar senha de Ajustes</button></div><div id="settings-password-result" class="result" role="status" aria-live="polite"></div></div><div class="card password-card"><h2>Senha de entrada no painel</h2><p class="muted">Altere a senha usada para entrar neste portal. Depois da troca, você precisará entrar novamente. A senha semanal dos tablets não muda.</p><form id="change-panel-password"><label class="field" for="current-panel-password">Senha atual do painel</label><input id="current-panel-password" type="password" autocomplete="current-password" required maxlength="256"><label class="field" for="new-panel-password">Nova senha do painel</label><input id="new-panel-password" type="password" autocomplete="new-password" required minlength="12" maxlength="256"><label class="field" for="confirm-panel-password">Confirmar nova senha</label><input id="confirm-panel-password" type="password" autocomplete="new-password" required minlength="12" maxlength="256"><button class="primary" type="submit">Alterar senha do painel</button><p id="change-password-result" class="error" role="status" aria-live="polite"></p></form></div><footer>Por segurança, as senhas mostradas nesta página desaparecem após um minuto.</footer></section>
<section class="view" id="errors" hidden><div class="hero"><div class="eyebrow">Diagnóstico</div><h1>Logs do sistema</h1><p>Falhas recentes de sincronização, armazenamento e funcionamento dos tablets.</p></div><div class="card"><h2>Erros do sistema</h2><p class="muted">Erros de impressão ficam no menu ao lado. Os registros não incluem senhas ou nomes de clientes.</p><div class="actions"><button class="secondary" id="reload-errors" type="button">Atualizar logs</button></div><div id="errors-result" class="result logs" role="status" aria-live="polite"></div></div></section>
<section class="view" id="printing" hidden><div class="hero"><div class="eyebrow">Diagnóstico</div><h1>Logs de impressão</h1><p>Falhas ao imprimir comandas ou testar a impressora.</p></div><div class="card"><h2>Erros de impressão</h2><p class="muted">Abertura da janela de impressão não confirma que o papel saiu; apenas falhas são registradas aqui.</p><div class="actions"><button class="secondary" id="reload-printing" type="button">Atualizar logs</button></div><div id="printing-result" class="result logs" role="status" aria-live="polite"></div></div></section></main>
<script nonce="${nonce}">
const idleMs=3600000;let lastActivity=Date.now(),lastRenew=Date.now();const passwordResult=document.querySelector('#password-result'),settingsPasswordResult=document.querySelector('#settings-password-result');let clearPassword,clearSettingsPassword;
async function leave(reason){passwordResult.textContent='';settingsPasswordResult.textContent='';try{await fetch('/admin/logout',{method:'POST',credentials:'same-origin',cache:'no-store'})}finally{location.replace('/admin?'+reason+'=1')}}
function expired(){return Date.now()-lastActivity>=idleMs}
function activity(){if(expired()){void leave('expired');return}lastActivity=Date.now();if(Date.now()-lastRenew>300000){lastRenew=Date.now();void fetch('/admin/session',{credentials:'same-origin',cache:'no-store'}).then(response=>{if(response.status===401)location.replace('/admin?expired=1')}).catch(()=>{})}}
for(const event of ['pointerdown','keydown','touchstart','scroll'])document.addEventListener(event,activity,{passive:true});setInterval(()=>{if(expired())void leave('expired')},30000);document.addEventListener('visibilitychange',()=>{passwordResult.textContent='';settingsPasswordResult.textContent='';if(!document.hidden&&expired())void leave('expired')});
async function request(url,options={}){if(expired()){await leave('expired');return null}const response=await fetch(url,{credentials:'same-origin',cache:'no-store',...options});if(response.status===401){location.replace('/admin?expired=1');return null}if(!response.ok)throw Error();return response.json()}
function showView(){const selected=location.hash.slice(1);const view=['password','errors','printing'].includes(selected)?selected:'password';for(const section of document.querySelectorAll('.view'))section.hidden=section.id!==view;for(const link of document.querySelectorAll('.nav a'))link.setAttribute('aria-current',link.dataset.view===view?'page':'false');passwordResult.textContent='';settingsPasswordResult.textContent='';if(view!=='password')void loadLogs(view)}
window.addEventListener('hashchange',showView);showView();
document.querySelector('#view').addEventListener('click',()=>void showPassword(false));document.querySelector('#rotate').addEventListener('click',()=>void showPassword(true));async function showPassword(rotate){if(rotate&&!confirm('Gerar outra senha agora? Os aparelhos conectados passarão a usar a nova senha.'))return;const buttons=[document.querySelector('#view'),document.querySelector('#rotate')];buttons.forEach(button=>button.disabled=true);passwordResult.textContent='Consultando…';try{const data=await request('/auth/admin/password',{method:rotate?'POST':'GET'});if(!data)return;passwordResult.textContent='Usuário: admin\\nSenha: '+data.password+'\\nPróxima troca: '+new Date(data.nextRotation).toLocaleString('pt-BR');clearTimeout(clearPassword);clearPassword=setTimeout(()=>{passwordResult.textContent=''},60000)}catch{passwordResult.textContent='Não foi possível consultar. Confira a conexão.'}finally{buttons.forEach(button=>button.disabled=false)}}
document.querySelector('#view-settings-password').addEventListener('click',()=>{const now=new Date(),month=now.getMonth()+1,day=now.getDate(),year=now.getFullYear(),hour=now.getHours()%12||12;settingsPasswordResult.textContent=['Senha de Ajustes: '+(month+day+year+hour),'Conta: '+month+' + '+day+' + '+year+' + '+hour,'Hora local: '+now.toLocaleString('pt-BR')].join(String.fromCharCode(10));clearTimeout(clearSettingsPassword);clearSettingsPassword=setTimeout(()=>{settingsPasswordResult.textContent=''},60000)});
document.querySelector('#change-panel-password').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),result=document.querySelector('#change-password-result');const currentPassword=document.querySelector('#current-panel-password').value,newPassword=document.querySelector('#new-panel-password').value,confirmPassword=document.querySelector('#confirm-panel-password').value;result.textContent='';if(newPassword!==confirmPassword){result.textContent='A confirmação não corresponde à nova senha.';return}button.disabled=true;try{const response=await fetch('/admin/change-password',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword,confirmPassword})});const data=await response.json();if(response.ok){form.reset();location.replace('/admin?changed=1');return}if(response.status===401){location.replace('/admin?expired=1');return}result.textContent=data.error||'Não foi possível alterar a senha.'}catch{result.textContent='Não foi possível alterar a senha. Confira a conexão.'}finally{button.disabled=false}});
async function loadLogs(kind){const result=document.querySelector('#'+kind+'-result');result.textContent='Carregando…';try{const rows=await request('/admin/logs?kind='+kind);if(!rows)return;result.textContent='';if(!rows.length){result.textContent='Nenhum erro recente.';return}for(const row of rows){const item=document.createElement('div');item.className='log';item.textContent=new Date(row.created_at).toLocaleString('pt-BR')+' · '+row.event+' · '+row.code+(row.order_id?' · Pedido '+row.order_id:'');result.appendChild(item)}}catch{result.textContent='Não foi possível consultar os registros.'}}
document.querySelector('#reload-errors').addEventListener('click',()=>void loadLogs('errors'));document.querySelector('#reload-printing').addEventListener('click',()=>void loadLogs('printing'));
document.querySelector('#logout').addEventListener('click',()=>void leave('loggedout'));
</script>`, nonce);
}
