import { LANGUAGES, translate, localizeMarkup, languageSelector, languageScript } from './manager-i18n.mjs';
import { dashboardContent, dashboardCss, dashboardScript } from './manager-dashboard.mjs';
const escape = value => String(value).replace(/[&<>'\u0022]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\u0022': '&quot;', "'": '&#39;' })[char]);
const css = `*{box-sizing:border-box}body{margin:0;background:#f6f5ef;color:#18392e;font:16px system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:wrap}h1{font-size:28px}h2{font-size:21px}section,article{background:white;border:1px solid #dfe5df;border-radius:14px;padding:22px;margin:18px 0}label{display:block;margin:12px 0}input,select,button{font:inherit;padding:10px;border:1px solid #bac8bf;border-radius:7px}input:not([type=checkbox]),select{max-width:100%;display:block;width:340px;margin-top:6px}button{cursor:pointer;background:#245c43;color:white;margin:8px 8px 8px 0}a{color:#245c43}small,.muted{color:#59685e}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.grid article{margin:0}.number{font-size:28px;font-weight:700}table{width:100%;border-collapse:collapse;font-size:14px}td,th{padding:11px;text-align:left;border-bottom:1px solid #e6ece7}.scroll{overflow:auto}#message{white-space:pre-wrap;min-height:24px;color:#a22828}.language-picker select{width:180px}.language-picker{margin:8px 0}#language-message:empty{display:none}#language-message{color:#a22828}.stores label{display:inline-flex;align-items:center;gap:8px;margin-right:16px}.stores input{margin:0}fieldset{border:1px solid #dfe5df;border-radius:8px}`;
export function page(nonce, content, script = '', extraCss = '', language = 'pt') {
  return `<!doctype html><html lang='${LANGUAGES[language]}'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>BistroHub · ${translate(language, 'Painel do Gestor')}</title><style nonce='${nonce}'>${css}${extraCss}</style></head><body><main>${content}</main>${script ? `<script nonce='${nonce}'>${script}</script>` : ''}</body></html>`;
}
export function managerLoginPage(nonce, csrf, message = '', language = 'pt') {
  return page(nonce, localizeMarkup(`<header><h1>BistroHub · Painel do Gestor</h1></header>${languageSelector(language)}<section><h2>Entrar</h2><p>O acesso é cadastrado pela administração do BistroHub.</p><p role='alert'>${escape(message)}</p><form action='/gestor/login' method='post'><input type='hidden' name='csrf' value='${escape(csrf)}'><label>Usuário<input name='username' autocomplete='username' required maxlength='24' autocapitalize='none'></label><label>Senha<input name='password' type='password' autocomplete='current-password' required maxlength='256'></label><button>Entrar</button></form></section>`, language), languageScript(language, '', 'manager', true), '', language);
}
const fetchHelper = `const $=s=>document.querySelector(s);async function api(path,body){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(response.status===401){location.replace(ADMIN?'/admin':'/gestor');throw Error(typeof tr==='function'?tr('Sessão encerrada.'):'Sessão encerrada.')}const value=await response.json();if(!response.ok)throw Error(typeof tr==='function'?tr(value.error||'Não foi possível concluir.'):value.error||'Não foi possível concluir.');return value}function option(select,id,name){const node=document.createElement('option');node.value=id;node.textContent=name;select.append(node)}function message(error){$('#message').textContent=error.message} `;
export function managerAdminPage(nonce, language = 'pt') {
  return page(nonce, localizeMarkup(`<header><h1>Acessos ao Painel do Gestor</h1><a href='/admin'>Voltar ao administrativo</a></header>${languageSelector(language)}<p>Cadastre o cliente ou grupo, vincule suas lojas e crie os usuários. A liberação dos módulos continua nas configurações de cada loja, no administrativo.</p><p id='message' role='status'></p><div class='grid'><section><h2>Cliente / grupo de lojas</h2><label>Cadastro<select id='client-picker'><option value=''>Novo cliente</option></select></label><form id='client-form'><label>Nome<input id='client-name' maxlength='100' required></label><label><input type='checkbox' id='client-active' checked> Acesso ativo</label><fieldset><legend>Lojas autorizadas</legend><div id='stores' class='stores'></div></fieldset><button>Salvar cliente</button></form></section><section><h2>Usuário gestor</h2><label>Cadastro<select id='user-picker'><option value=''>Novo usuário</option></select></label><form id='user-form'><label>Cliente / grupo<select id='user-client' required></select></label><label>Nome<input id='user-name' maxlength='100' required></label><label>Usuário<input id='user-username' maxlength='24' pattern='[a-z0-9][a-z0-9._-]{2,23}' autocapitalize='none' autocomplete='off' required></label><label>Senha inicial ou nova senha<input id='user-password' type='password' minlength='12' maxlength='256' autocomplete='new-password'></label><small>Ao editar, deixe a senha vazia para mantê-la. Use pelo menos 12 caracteres. Entregue o acesso diretamente ao cliente.</small><label><input type='checkbox' id='user-active' checked> Usuário ativo</label><button>Salvar usuário</button></form></section></div><section><h2>Portal do cliente</h2><p><a href='/gestor' target='_blank' rel='noopener'>Abrir o Painel do Gestor</a></p><p>Alterar lojas, desativar um acesso ou redefinir uma senha encerra as sessões anteriores. Cada usuário consulta somente as lojas do seu cliente.</p></section>`, language), `${languageScript(language, '', 'admin')}const ADMIN=true;${fetchHelper}
let clients=[],users=[];function currentClient(){return clients.find(c=>c.id===$('#client-picker').value)}function currentUser(){return users.find(u=>u.id===$('#user-picker').value)}
function fillClient(){const c=currentClient();$('#client-name').value=c?.name||'';$('#client-active').checked=c?.active??true;document.querySelectorAll('[data-store]').forEach(node=>node.checked=c?.storeIds.includes(node.value)||false)}
function fillUser(){const u=currentUser();$('#user-name').value=u?.name||'';$('#user-username').value=u?.username||'';$('#user-username').readOnly=!!u;$('#user-client').value=u?.clientId||clients[0]?.id||'';$('#user-active').checked=u?.active??true;$('#user-password').value='';$('#user-password').required=!u}
async function load(clientId='',userId=''){const data=await api('/admin/manager-clients');clients=data.clients;users=(await api('/admin/manager-users')).users;$('#client-picker').replaceChildren();option($('#client-picker'),'',tr('Novo cliente'));$('#user-client').replaceChildren();clients.forEach(c=>{option($('#client-picker'),c.id,c.name+(c.active?'':' · '+tr('inativo')));option($('#user-client'),c.id,c.name+(c.active?'':' · '+tr('inativo')))});$('#user-picker').replaceChildren();option($('#user-picker'),'',tr('Novo usuário'));users.forEach(u=>option($('#user-picker'),u.id,u.name+' · '+u.username+(u.active?'':' · '+tr('inativo'))));$('#stores').replaceChildren();data.stores.forEach(s=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=s.id;input.dataset.store='';label.append(input,document.createTextNode(s.name));$('#stores').append(label)});$('#client-picker').value=clientId;$('#user-picker').value=userId;fillClient();fillUser()}
$('#client-picker').onchange=fillClient;$('#user-picker').onchange=fillUser;
$('#client-form').onsubmit=async e=>{e.preventDefault();try{const c=currentClient(),result=await api('/admin/manager-clients',{...(c?{id:c.id,revision:c.revision}:{}),name:$('#client-name').value,active:$('#client-active').checked,storeIds:[...document.querySelectorAll('[data-store]:checked')].map(n=>n.value)});await load(result.client.id);$('#message').textContent=tr('Cliente salvo.')}catch(error){message(error)}};
$('#user-form').onsubmit=async e=>{e.preventDefault();try{const u=currentUser(),result=await api('/admin/manager-users',{...(u?{id:u.id,revision:u.revision}:{}),clientId:$('#user-client').value,name:$('#user-name').value,username:$('#user-username').value,password:$('#user-password').value,active:$('#user-active').checked});$('#user-password').value='';await load($('#client-picker').value,result.user.id);$('#message').textContent=tr('Usuário salvo.')}catch(error){message(error)}};void load().catch(message);`, '', language);
}
export function managerPortalPage(nonce, session, language = 'pt') {
  return page(nonce, localizeMarkup(dashboardContent(escape, session).replace("<p id='message'", languageSelector(language) + "<p id='message'"), language), `${languageScript(language, session.user.id)}const ADMIN=false;${fetchHelper}${dashboardScript}`, dashboardCss, language);
}
